main:
  params:
    - input
  steps:

    - init:
        assign:
          - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: "us-east1"
          - job_name: "step-1-quality-filter-job"
          - bucket: ${input.bucket}
          - prefix: ${input.prefix}
          - version: ${input.version}
          - topic: ${"projects/" + project + "/topics/image-processing-step-1-topic"}
          - pageToken: null
          - publishedCount: 0

    - log_init:
        call: sys.log
        args:
          text: ${"🚀 Workflow started | bucket=" + bucket + " | prefix=" + prefix + " | version=" + version}
          severity: INFO

    - list_objects:
        call: googleapis.storage.v1.objects.list
        args:
          bucket: ${bucket}
          prefix: ${prefix}
          pageToken: ${pageToken}
          maxResults: 100        # 🔑 CLAVE PARA MEMORIA
        result: objects
    
    - normalize_images:
        switch:
          - condition: ${objects.items == null}
            next: handle_pagination
        next: publish_images

    - publish_images:
        for:
          value: obj
          in: ${objects.items}
          steps:

            - build_payload:
                assign:
                  - payload:
                      version: ${version}
                      bucket: ${bucket}
                      input_path: ${"gs://" + bucket + "/" + obj.name}
                      step: "step-1"

            - publish_message:
                call: googleapis.pubsub.v1.projects.topics.publish
                args:
                  topic: ${topic}
                  body:
                    messages:
                      - data: ${base64.encode(json.encode(payload))}
            - log_published:
                call: sys.log
                args:
                  text: ${"Publicado gs://" + bucket + "/" + obj.name}
                  severity: DEBUG

            - inc_counter:
                assign:
                  - publishedCount: ${publishedCount + 1}

    - handle_pagination:
        switch:
          - condition: ${"nextPageToken" in objects}
            next: set_next_page
        next: trigger_job


    - set_next_page:
        assign:
          - pageToken: ${objects.nextPageToken}
        next: list_objects

    # 🚀 NUEVO PASO CLAVE
    - trigger_job:
        call: http.post
        args:
          url: ${"https://run.googleapis.com/v2/projects/" + project + "/locations/us-east1/jobs/step-1-quality-filter-job:run"}
          auth:
            type: OAuth2
          body: {}
        result: job_execution

    - log_job:
        call: sys.log
        args:
          text: ${"🔥Se termino de ejecutar el JOB"}
          severity: INFO

    - done:
        return:
          status: "OK"
          images_published: ${publishedCount}


